server:
  port: 9000
  undertow:
    accesslog:
      enabled: true
      dir: '/var/log/natWest'
  compression:
    enabled: true
  error:
    whitelabel:
      enabled: false
  http2:
    enabled: true
  servlet:
    application-display-name: NatWest Transaction Writer
    encoding:
      charset:
  shutdown: graceful

natWestTransactionReader:
  log-file-path: '/var/log/natWest/writer.log'
  swagger:
    app-name: NatWest Transaction Writer
    realm: api-realm
    title: NatWest Transaction Writer API
    description: Documentation of NatWest Transaction Writer API.
    term-of-service-url: Terms of service
    version: 1.0.0
    contact-name: Divyanshu
    contact-email: divyanshuok@outlook.com

spring:
  datasource:
    tomcat:
      max-wait: 20000
      max-active: 50
      max-idle: 20
      min-idle: 15
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/natwest_transaction?allowPublicKeyRetrieval=true&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    mapper:
      ACCEPT_CASE_INSENSITIVE_ENUMS: true
    default-property-inclusion: NON_EMPTY

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL5Dialect
    open-in-view: true

  output:
    ansi:
      enabled: ALWAYS

logging:
  level:
    org:
      hibernate:
        SQL: INFO
        type:
          descriptor:
            sql:
              BasicBinder: INFO



